### ISSUE TITLE
allow for unzipped config

### ISSUE THREAD

**Issue by blaggacao** [CyCoreSystems/asterisk-config#11]
I want to be able to construe `/source` directly from one or several configmaps / secrets without the need to package them as zip file previously. So that I can use kubernetes native (_kustomize_) gitops workflows (I could write my own _kustomize_ zip generator, though) and factor configuration into layers through (_kustomize_) `merge` directives:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./00-rbac.yaml
- ./01-nats.yaml
- ./02-kamailio.yaml
- ./03-asterisk.yaml
secretGenerator:
- name: asterisk-config-base
  namespace: voip
  behavior: [create|replace|merge]  # this allows me to better factor configuration into pieces
  files:
  - modules.conf=asteriskconfig/modules.conf

- name: asterisk-config-ari.d
  namespace: voip
  behavior: [create|replace|merge]  # this allows me to better factor configuration into pieces
  files:
  - admin.conf=asteriskconfig/ari.d/admin.conf

- name: asterisk-config-pjsip.d
  namespace: voip
  behavior: [create|replace|merge]  # this allows me to better factor configuration into pieces
  files:
  - proxies.conf.tmpl=asteriskconfig/pjsip.d/proxies.conf.tmpl

- name: asterisk-config-extensions.d
  namespace: voip
  behavior: [create|replace|merge]  # this allows me to better factor configuration into pieces
  files:
  - inbound.conf.tmpl=asteriskconfig/extensions.d/inbound.conf.tmpl
```

```yaml
    spec:
      volumes:
        - name: config
          emptyDir: {}
        - name: custom-base
          secret:
            secretName: asterisk-config-base
        - name: custom-ari-d
          secret:
            secretName: asterisk-config-ari.d
        - name: custom-pjsip-d
          secret:
            secretName: asterisk-config-pjsip.d
        - name: custom-extensions-d
          secret:
            secretName: asterisk-config-extensions.d
      containers:
        - name: config
          image: cycoresystems/asterisk-config
          volumeMounts:
            - name: config
              mountPath: /etc/asterisk
            - name: custom-base
              mountPath: /source
            - name: custom-arid
              mountPath: /source/ari.d
            - name: custom-pjsipd
              mountPath: /source/pjsip.d
            - name: custom-extensions-d
              mountPath: /source/extensions.d

```
